version: '3.9'

services:
  flask_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask_audio_processor
    ports:
      - "5000:5000" 
    volumes:
      - ./uploads:/app/uploads 
    environment:
      FLASK_ENV: development
    restart: always

volumes:
  uploads:
